apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop-deployment
  namespace: kafka
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kafdrop-deployment
  template:
    metadata:
      labels:
        app: kafdrop-deployment
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka:9092"
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
          ports:
            - containerPort: 9000
              name: kafdrop-port