apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: database
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
