apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: database
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
    - name: metrics
      port: 9104
      targetPort: metrics
      protocol: TCP
