apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-conf
    namespace: database
data:
    my.cnf: ENC[AES256_GCM,data:6nwhhP4Ac16wYebm78ukVKc3vabPqZLcR2I0I3Gwhr9CB7JQM7tvQ9Nks/y7FiQZgCFj3DZ72lp1QUrGBNJvZfg2YNz980MBJocXAAyjSX12KPa0EZh6K/9onYfVj7P47pRXE6/wsLOTgeitMYbzJ3/tz6+/3oZY32UEcnpAQVeE0c9xOGCrbBSNnLIJuy+OvKeZnF4lfO71901PQwFrYROGiIqwEvieNzStCpmkMELKsra3e+YPlEZP0A4JQh6Jk81n78MaIsV2d24fTiioKYAfpuCwh37pO1ry7Cgl5mjAVkq7HmPEsB3Ja7trm+RpcpUdiPt/W3FYjhKCpfBjjUGTruqfOx5/HyZ4O/FM/TUFLiaAsAHawQg5kA7dElwOtkOBCM5a7rcYR4CZr+x+X+Ec3ch4sKTyQWaBU0dKZbcnkhlRhFK3+XoL4i8mAonQH920hQycHS268dEjBea/sUp5f4d+YdyOkofWctWpv+iNnOLWa9c7BR2uA4fLm7Xhv5YCTX1d9JXX7f9z4ScoqrTxZt34lpImmh9VLcJ3vJCdPLjuY/7az7GKKxVeEqPgul+AoKpNkdEI3LN2cbsnBjE2Q9EAmmBM5MXLj+avDXea/cqEofrCfWrk3C2M04V2uWKkUT/wdhWPVJX0qP3fiy5Zn6JeGjFhI2UGtJXj06F51we0+C53FIa2ay/VLJ8gy0Apm074lEoGyTrj4WlHFcOkNJVafrIMap4Db1IL5+SiVnii6uA+m6prwH6tUeUoV5m6mdOmWcX0vomIZzlA5vr9avqrbf2fD3szxpcrok2pI8RtRZ3qvov5PobenVXtqt7liqQLZMugbgvW/TPlPgz0OuFQMY1iGEhYURGAYzWVqW/u03F+ba7vlzQtHAaViai9DjacZ7XaTWoG/t5XGYONPfRYB22Eqn/VMbySpJ18XDCvkPM2xnlUsdpM8Rgsh/bjh1lg3TgueozZrUQmh2w9m0gM68gxVEbmq8TcGaGZTR3UXFGo4fVQ3/h+UvpoHX0NU7l5in6qewxaxuq3hh/fh9xSQlN/ycl0wHq7m8E3MFeObd619P0Zg4WBg4kD2hKGOvKZckCFP9EBG2hB51xw8acOyaigdgn+x5TrBeDb5F4Ya7BN7p8INBNK1VoPE3Wk1Z53/ufpXpvVpTpM7B5ik8C4X5LXZ1G5OF7I4S9nug==,iv:9v8lIu3qJijixgVVqNv4JozbQEkOZ51GBIKLIOtahfs=,tag:f4IbTbikvtrVgAfGsA9ARQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg7ucj959d4v7l7raqm8v3rcrl2gp87tmyek3dvuyjh3nqk4he3sqx2yqa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRWwvK1NFYlJxV3lZQklP
            NzcxeE1JQzd4Zm93Y0E2b3hYRWlmdW9ZbnhvCnJDM2NxRkNwOGwyRmJsWHNCY0hS
            cnJWRlJucWpKYTVXYVNPWlkxT2xLNEUKLS0tIDB4ZDc0M3JIZ04rLytuRU1aTzY4
            Q1Y3RHRhM2pPU2dDbUJuNktLaHhZQ1UKOJvmg7Uxa8AAbFSami+cEyZ8cLdHmBze
            nFx0jU6VyNnGYd4iPzJO6AlkWVmRiylqQ7ljFQwH1HkdyTLS3Ne6sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-19T03:30:47Z"
    mac: ENC[AES256_GCM,data:dA/InuIS8KlYbzj6UPTNwm6NC/efsJ/xP5JniRHPUQ7lG9VJOp0lzrYicGv4E/yHGx+Bi2318NUYBn1Cs3/oooFB2xFSLqbwVX7IRYpJ1Sm7C7oKMFSONA8tOjG5UunCBgTz2UTBTQpk2eriK2exy4TTVAHPGAze7MfHcdoOxGw=,iv:qqEDN1Y9bn5RqQA7B+zBRwQVuzBwGvaKCAABE/mVKpo=,tag:IUksMByKnN0gUpb7WzhEcA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
