apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-rbac
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Bot-detector/bot-detector-k8s.git
    targetRevision: HEAD
    path: kubernetes/rbac
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
