apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-dvp-api
  namespace: dvp
spec:
  selector:
    matchLabels:
      app: bd-dvp-api
  replicas: 0
  template:
    metadata:
      labels:
        app: bd-dvp-api
    spec:
      containers:
        - name: bd-dvp-api
          image: quay.io/bot_detector/bd-core-files:c84373a
          ports:
            - containerPort: 5000
          env:
            - name: discord_sql_uri
              valueFrom:
                secretKeyRef:
                  name: bd-dvp-api-secret
                  key: discord_sql_uri
            - name: sql_uri
              valueFrom:
                secretKeyRef:
                  name: bd-dvp-api-secret
                  key: sql_uri
            - name: token
              valueFrom:
                secretKeyRef:
                  name: bd-dvp-api-secret
                  key: token
