apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-dvp-api
  namespace: bd-dvp
spec:
  selector:
    matchLabels:
      app: bd-dvp-api
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bd-dvp-api
    spec:
      containers:
        - name: bd-dvp-api
          image: quay.io/bot_detector/bd-core-files:930e477
          ports:
            - name: dvp-api-port
              containerPort: 5000
          env:
            - name: discord_sql_uri
              valueFrom:
                secretKeyRef:
                  name: bd-dvp-api-secret
                  key: discord_sql_uri
            - name: sql_uri
              valueFrom:
                secretKeyRef:
                  name: bd-dvp-api-secret
                  key: sql_uri
            - name: token
              valueFrom:
                secretKeyRef:
                  name: bd-dvp-api-secret
                  key: token
            - name: kafka_url
              value: kafka-service.kafka.svc:9092
