apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bd-dvp-api-ingress
  namespace: bd-dvp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.dev.osrsbotdetector.com
      secretName: api-tls
  rules:
    - host: api.dev.osrsbotdetector.com
      http:
        paths:
          - path: /docs(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: bd-dvp-api-service
                port:
                  name: dvp-api-port
          - path: /(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: bd-dvp-api-service
                port:
                  name: dvp-api-port
