apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-api
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: private-api
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: private-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql
                topologyKey: kubernetes.io/hostname
      containers:
        - name: private-api
          image: quay.io/bot_detector/private-api:cf68297
          resources:
            requests:
              cpu: 500m
              memory: 150M
          ports:
            - name: priv-api-port
              containerPort: 5000
          env:
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
            - name: env
              value: PRD
            - name: POOL_RECYCLE
              value: '50'
            - name: POOL_TIMEOUT
              value: '25'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bd-prd-api-secret
                  key: sql_uri
          livenessProbe:
            httpGet:
              path: /
              port: priv-api-port
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: priv-api-port
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 3
            timeoutSeconds: 5
