apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: bd-prd-api-alerts
  namespace: bd-prd
spec:
  groups:
    - name: api-ingress
      rules:
        - alert: core_api_too_many_500s
          annotations:
            description: Too many 5XXs
            summary: More than 5% of all requests returned 5XX, this may require your attention
          expr: 100 * ( sum(nginx_ingress_controller_requests{status=~"5.+", ingress="bd-prd-api-ingress"}) / sum(nginx_ingress_controller_requests{ingress="bd-prd-api-ingress"}) ) > 5
          for: 1m
          labels:
            severity: warning
        - alert: core_api_too_many_400s
          annotations:
            description: Too many 4XXs
            summary: More than 5% of all requests returned 4XX, this may require your attention
          expr: 100 * ( sum(nginx_ingress_controller_requests{status=~"4.+", ingress="bd-prd-api-ingress"}) / sum(nginx_ingress_controller_requests{ingress="bd-prd-api-ingress"}) ) > 5
          for: 1m
          labels:
            severity: warning
        - alert: core_api_low_request_rate
          annotations:
            description: Request rate is too low
            summary: The request rate to the API ingress is 5 or less requests per second over the past 2 minutes
          expr: sum(irate(nginx_ingress_controller_requests{ingress=~"bd-prd-api-ingress"}[1m])) <= 5
          for: 1m
          labels:
            severity: warning
