apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-api
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-api
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bd-prd-api
    spec:
      containers:
        - name: bd-prd-api
          image: quay.io/bot_detector/bd-core-files:acf5de4
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 2
          ports:
            - name: prd-api-port
              containerPort: 5000
          env:
            - name: discord_sql_uri
              valueFrom:
                secretKeyRef:
                  name: bd-prd-api-secret
                  key: discord_sql_uri
            - name: sql_uri
              valueFrom:
                secretKeyRef:
                  name: bd-prd-api-secret
                  key: sql_uri
            - name: token
              valueFrom:
                secretKeyRef:
                  name: bd-prd-api-secret
                  key: token
            - name: kafka_url
              value: kafka-service.kafka.svc:9092
            - name: env
              value: PRD
          livenessProbe:
            httpGet:
              path: /
              port: prd-api-port
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: prd-api-port
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 3
            timeoutSeconds: 5
