apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-api
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-api
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bd-prd-api
    spec:
      containers:
        - name: bd-prd-api
          image: quay.io/bot_detector/bd-core-files:4a31900
          ports:
            - name: prd-api-port
              containerPort: 5000
          env:
            - name: discord_sql_uri
              valueFrom:
                secretKeyRef:
                  name: bd-prd-api-secret
                  key: discord_sql_uri
            - name: sql_uri
              valueFrom:
                secretKeyRef:
                  name: bd-prd-api-secret
                  key: sql_uri
            - name: token
              valueFrom:
                secretKeyRef:
                  name: bd-prd-api-secret
                  key: token
