apiVersion: v1
kind: Service
metadata:
  name: bd-prd-api-service
  namespace: bd-prd
  labels:
    app: bd-prd-api
spec:
  type: ClusterIP
  selector:
    app: bd-prd-api
  ports:
    - name: prd-api-port # alias listening
      port: 5000 #  [listening] the container port exposed by a pod or deployment,
      protocol: TCP
      targetPort: prd-api-port # [sending] the port on the host machine that traffic is directed to
