apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-web
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-web
  replicas: 0
  template:
    metadata:
      labels:
        app: bd-prd-web
    spec:
      containers:
        - name: bd-prd-web
          image: quay.io/bot_detector/bd-web:a9d07b6
          ports:
            - containerPort: 8080
          env:
            - name: VITE_BOTDETECTOR_API_URL
              valueFrom:
                secretKeyRef:
                  key: VITE_BOTDETECTOR_API_URL
                  name: bd-dvp-web-secret
            - name: VITE_RUNELITE_API_URL
              valueFrom:
                secretKeyRef:
                  key: VITE_RUNELITE_API_URL
                  name: bd-dvp-web-secret
