apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-web
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-web
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bd-prd-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - mysql
            topologyKey: "kubernetes.io/hostname"
        - name: bd-prd-web
          image: quay.io/bot_detector/bd-web:89ad226
          ports:
            - name: prd-web-port
              containerPort: 8000
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: bd-prd-web-secret
