apiVersion: v1
kind: Service
metadata:
  name: bd-prd-web-service
  namespace: bd-prd
spec:
  selector:
    app: bd-prd-web
  ports:
    - name: prd-web-port
      port: 8000
      protocol: TCP
      targetPort: prd-web-port
