apiVersion: v1
kind: Service
metadata:
  name: bd-prd-web-service
  namespace: bd-prd
spec:
  selector:
    app: bd-prd-web
  ports:
    - name: web-port
      port: 8080
      protocol: TCP
      targetPort: web-port
