apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-highscore
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: scraper-highscore
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: scraper-highscore
    spec:
      containers:
        - name: scraper-highscore
          image: quay.io/bot_detector/scraper-highscore:409b20a
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
          env:
            - name: PROXY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: PROXY_API_KEY
                  name: bd-prd-scraper-secret
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
            - name: SESSION_TIMEOUT
              value: '60'
