apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-highscore
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: scraper-highscore
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: scraper-highscore
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql
                topologyKey: kubernetes.io/hostname
      containers:
        - name: scraper-highscore
          image: quay.io/bot_detector/scraper-highscore:5b4a15f
          resources:
            requests:
              cpu: 200m
              memory: 150Mi
          ports:
            - name: metrics
              containerPort: 8000
          env:
            - name: PROXY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: PROXY_API_KEY
                  name: bd-prd-scraper-secret
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service.kafka.svc:9092
            - name: SESSION_TIMEOUT
              value: '60'
