apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scraper-highscore
  namespace: bd-prd
spec:
  endpoints:
    - path: /
      port: scraper-hs-metrics
  selector:
    matchLabels:
      app: scraper-highscore