apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: kafka
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: zookeeper-deployment
  template:
    metadata:
      labels:
        app: zookeeper-deployment
    spec:
      containers:
        - name: zookeeper
          image: ubuntu/zookeeper:edge
          ports:
            - name: zookeeper-port
              containerPort: 2181
              protocol: TCP