apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: kafka
spec:
  selector:
    app: zookeeper-deployment
  ports:
    - name: zookeeper-port
      port: 2181
      protocol: TCP
      targetPort: zookeeper-port
