apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-runemetrics
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: scraper-runemetrics
  replicas: 4
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: scraper-runemetrics
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - mysql
            topologyKey: "kubernetes.io/hostname"
        - name: scraper-runemetrics
          image: quay.io/bot_detector/scraper-runemetrics:5b19cb1
          resources:
            requests:
              cpu: 500m
              memory: 150Mi
            limits:
              cpu: 1
          env:
            - name: PROXY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: PROXY_API_KEY
                  name: bd-prd-scraper-secret
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
            - name: SESSION_TIMEOUT
              value: '60'
