apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-runemetrics
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: scraper-runemetrics
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: scraper-runemetrics
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql
                topologyKey: kubernetes.io/hostname
      containers:
        - name: scraper-runemetrics
          image: quay.io/bot_detector/scraper-runemetrics:2d278d7
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: metrics
              containerPort: 8000
          env:
            # kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service.kafka.svc:9092
            # proxy
            - name: PROXY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: PROXY_API_KEY
                  name: bd-prd-scraper-secret
            - name: MAX_CALLS
              value: '15'
            - name: INTERVAL
              value: '60'
