apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scraper-rm
  namespace: bd-prd
spec:
  endpoints:
    - path: /
      port: metrics
  selector:
    matchLabels:
      app: scraper-runemetrics