apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-dvp-web
  namespace: bd-dvp
spec:
  selector:
    matchLabels:
      app: bd-dvp-web
  replicas: 0
  template:
    metadata:
      labels:
        app: bd-dvp-web
    spec:
      containers:
        - name: bd-dvp-web
          image: quay.io/bot_detector/bd-web:e0a25e4
          ports:
            - containerPort: 8081
          env:
            - name: VITE_BOTDETECTOR_API_URL
              valueFrom:
                secretKeyRef:
                  key: VITE_BOTDETECTOR_API_URL
                  name: bd-dvp-web-secret
            - name: VITE_RUNELITE_API_URL
              valueFrom:
                secretKeyRef:
                  key: VITE_RUNELITE_API_URL
                  name: bd-dvp-web-secret
