apiVersion: v1
kind: Service
metadata:
  name: bd-dvp-web-service
  namespace: bd-dvp
spec:
  selector:
    app: bd-dvp-web
  ports:
    - name: web-port
      port: 8000
      protocol: TCP
      targetPort: web-port
