apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argo-cd
spec:
  project: default
  source:
    chart: hello-world
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
    helm:
      releaseName: test-chart
      valueFiles:
        - https://raw.githubusercontent.com/Bot-detector/bot-detector-k8s/develop/test/values.yaml
        - secrets://https://raw.githubusercontent.com/Bot-detector/bot-detector-k8s/develop/test/values.secret.yaml
        # secrets://secrets.yaml
        # secrets+age-import-kubernetes://<namespace>/<secret-name>#<key-name>.txt?<relative/path/to/the/encrypted/secrets.yaml>
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
