apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Bot-detector/bot-detector-k8s.git
      targetRevision: HEAD
      ref: bot-detector-k8s
    - chart: hello-world
      repoURL: https://helm.github.io/examples
      targetRevision: 0.1.0
      helm:
        releaseName: test-chart
        valueFiles:
          - $bot-detector-k8s/test/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
