apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-config-2
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Bot-detector/bot-detector-k8s.git
    targetRevision: HEAD
    path: test2
  destination:
    server: https://kubernetes.default.svc
    namespace: app-config-2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true