apiVersion: apps/v1
kind: Deployment
metadata:
  name: highscore-worker
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: highscore-worker
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: highscore-worker
    spec:
      containers:
        - name: highscore-worker
          image: quay.io/bot_detector/highscore-worker:c710a7c
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
          env:
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
            - name: POOL_TIMEOUT
              value: '25'
            - name: POOL_RECYCLE
              value: '25'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: highscore-worker
                  key: DATABASE_URL
