apiVersion: apps/v1
kind: Deployment
metadata:
  name: highscore-worker
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: highscore-worker
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: highscore-worker
    spec:
      containers:
        - name: highscore-worker
          image: quay.io/bot_detector/highscore-worker:b5eba0f
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1
          env:
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
            - name: POOL_TIMEOUT
              value: '25'
            - name: POOL_RECYCLE
              value: '25'
            - name: ENV
              value: PRD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: highscore-worker
                  key: DATABASE_URL
