apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argo-cd
  spec:
    destination:
      namespace: my-app
      server: https://kubernetes.default.svc
    project: my-project
    source:
      path: applications
      repoURL: https://github.com/Bot-detector/bot-detector-k8s.git
      targetRevision: HEAD
