apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
  namespace: bd-prd
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: public-api
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: public-api
    spec:
      containers:
        - name: public-api
          image: quay.io/bot_detector/public-api:a511796
          resources:
            requests:
              cpu: 500m
              memory: 150M
          ports:
            - name: public-api-port
              containerPort: 5000
          env:
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
            - name: env
              value: PRD
            - name: POOL_RECYCLE
              value: '60'
            - name: POOL_TIMEOUT
              value: '30'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bd-prd-api-secret
                  key: sql_uri
          livenessProbe:
            httpGet:
              path: /
              port: public-api-port
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: public-api-port
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 3
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /
              port: public-api-port
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
