apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: public-api
  namespace: bd-prd
  labels:
    app: public-api
spec:
  endpoints:
    - path: /
      port: metrics
  selector:
    matchLabels:
      app: public-api