apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-worker
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: report-worker
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: report-worker
    spec:
      containers:
        - name: report-worker
          image: quay.io/bot_detector/report-worker:be0e23d
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
          env:
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
            - name: POOL_TIMEOUT
              value: '25'
            - name: POOL_RECYCLE
              value: '25'
            - name: ENV
              value: PRD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: report-worker
                  key: DATABASE_URL
