apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-automation
spec:
  selector:
    matchLabels:
      app: bd-prd-automation
  replicas: 1
  template:
    metadata:
      labels:
        app: bd-prd-automation
    spec:
      containers:
        - name: bd-prd-automation
          image: quay.io/bot_detector/bd-automation-bot
