apiVersion: v1
kind: Service
metadata:
  name: ban-migration-worker
  namespace: bd-prd
  labels:
    app: ban-migration-worker
spec:
  type: ClusterIP
  selector:
    app: ban-migration-worker
  ports:
    - name: metrics # alias listening
      port: 8000 #  [listening] the container port exposed by a pod or deployment,
      protocol: TCP
      targetPort: metrics # [sending] the port on the host machine that traffic is directed to
