apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ban-migration-worker
  namespace: bd-prd
spec:
  endpoints:
    - path: /
      port: metrics
  selector:
    matchLabels:
      app: ban-migration-worker
