apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-report
  namespace: bd-prd
spec:
  endpoints:
    - path: /
      port: metrics
      interval: 30s
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app: worker-report
