apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-ml
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-ml
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bd-prd-ml
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql
                topologyKey: kubernetes.io/hostname
      containers:
        - name: bd-prd-ml
          image: quay.io/bot_detector/bd-ml:d93d606
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
          ports:
            - containerPort: 5000
              name: ml-api-port
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.minio.svc:9000
            - name: MODEL_URIS
              value: '{"multi_model_v1":"s3://models/m-a5a92f202d7945c0bb6584993d0242ac/artifacts"}'
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-ml-api
                  key: username
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-ml-api
                  key: password
