apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-kafka
  namespace: kafka
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bd-prd-kafka
  template:
    metadata:
      labels:
        app: bd-prd-kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9093
              name: kafka-controller
            - containerPort: 9094
              name: kafka-external
      