apiVersion: v1
kind: Service
metadata:
  name: bd-prd-kafka-service
  namespace: kafka
spec:
  selector:
    app: bd-prd-kafka
  ports:
    - name: kafka-external
      port: 9094
      protocol: TCP
      targetPort: kafka-external
---------------------------------
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  selector:
    app: bd-prd-kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: kafka