apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-discord
spec:
  selector:
    matchLabels:
      app: bd-prd-discord
  replicas: 1
  template:
    metadata:
      labels:
        app: bd-prd-discord
    spec:
      containers:
        - name: bd-prd-discord
          image: quay.io/bot_detector/bd-discord-bot:bed2adc
          ports:
            - containerPort: 3000
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: prd.discord
                  key: TOKEN
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: prd.discord
                  key: API_TOKEN
            - name: COMMAND_PREFIX
              valueFrom:
                secretKeyRef:
                  name: prd.discord
                  key: COMMAND_PREFIX
            - name: WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: prd.discord
                  key: WEBHOOK
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: prd.discord
                  key: API_URL
            - name: SQL_URI
              valueFrom:
                secretKeyRef:
                  name: prd.discord
                  key: SQL_URI