apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-discord
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-discord
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bd-prd-discord
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql
                topologyKey: kubernetes.io/hostname
      containers:
        - name: bd-prd-discord
          image: quay.io/bot_detector/bd-discord-bot:47d598f
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 3000
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: bd-prd-discord-secret
                  key: TOKEN
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bd-prd-discord-secret
                  key: API_TOKEN
            - name: COMMAND_PREFIX
              valueFrom:
                secretKeyRef:
                  name: bd-prd-discord-secret
                  key: COMMAND_PREFIX
            - name: WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: bd-prd-discord-secret
                  key: WEBHOOK
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: bd-prd-discord-secret
                  key: API_URL
            - name: SQL_URI
              valueFrom:
                secretKeyRef:
                  name: bd-prd-discord-secret
                  key: SQL_URI
