apiVersion: v1
kind: Service
metadata:
  name: bd-prd-discord-service
  namespace: prd
spec:
  selector:
    app: bd-prd-discord
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
