apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-dev-api
  namespace: app-config
spec:
  selector:
    matchLabels:
      app: bd-dev-api
  replicas: 1
  template:
    metadata:
      name: bd-dev-api
      labels:
        app: bd-dev-api
    spec:
      containers:
        - name: bd-dev-api
          image: quay.io/bot_detector/bd-core-files:549cd38
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: discord_sql_uri
              valueFrom:
                secretKeyRef:
                  name: core.files
                  key: discord_sql_uri
            - name: sql_uri
              valueFrom:
                secretKeyRef:
                  name: core.files
                  key: sql_uri
            - name: token
              valueFrom:
                secretKeyRef:
                  name: core.files
                  key: token
