apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-dev-api
  namespace: app-config
spec:
  selector:
    matchLabels:
      app: bd-dev-api
  replicas: 1
  template:
    metadata:
      name: bd-dev-api
      labels:
        app: bd-dev-api
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - bd-dev-api
                topologyKey: kubernetes.io/hostname
      containers:
        - name: bd-dev-api
          image: quay.io/bot_detector/bd-core-files:549cd38
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 500Mi
            limits:
              cpu: 2000m
              memory: 3000Mi
          env:
            - name: discord_sql_uri
              valueFrom:
                secretKeyRef:
                  name: core.files
                  key: discord_sql_uri
            - name: sql_uri
              valueFrom:
                secretKeyRef:
                  name: core.files
                  key: sql_uri
            - name: token
              valueFrom:
                secretKeyRef:
                  name: core.files
                  key: token
