apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: kafka
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kafka-deployment
  template:
    metadata:
      labels:
        app: kafka-deployment
    spec:
      containers:
        - name: kafka
          image: ubuntu/kafka:edge
          env:
            - name: ZOOKEEPER_HOST
              value: zookeeper-service
          args: ["/etc/kafka/server.properties", "--override", "advertised.listeners=PLAINTEXT://kafka-service:9092"]
          ports:
          - name: kafka-port
            containerPort: 9092
            protocol: TCP
      