apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  selector:
    app: kafka-deployment
  ports:
    - name: kafka-external
      port: 9094
      protocol: TCP
      targetPort: kafka-external