apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  selector:
    app: kafka-deployment
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
      targetPort: kafka-port
