# defining the .spec.capacity.stoage here and in the PVC could cause GitOps issues
# removing the capacity size here will work for already created objects
# since most tools do a Merge strategy, however it is a required field
# during initialization of the object, so it would have to be defined here then.
# TLDR parts of this design are not "best" practice

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zfs
  accessModes:
    - ReadWriteOnce
# capacity:
#   storage: 1Ti
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/cas-type: localpv-zfs
      openebs.io/poolname: tank/pv
    volumeHandle: mysql-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: openebs.io/nodeid
              operator: In
              values:
                - kube-worker-1
