apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: database
spec:
  storageClassName: zfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
