apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-scraper
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-scraper
  replicas: 0
  template:
    metadata:
      labels:
        app: bd-prd-scraper
    spec:
      containers:
        - name: bd-prd-scraper
          image: quay.io/bot_detector/bd-scraper:2511d28
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: bd-prd-scraper-secret
            - name: endpoint
              valueFrom:
                secretKeyRef:
                  key: endpoint
                  name: bd-prd-scraper-secret
            - name: PROXY_DOWNLOAD_URL
              valueFrom:
                secretKeyRef:
                  key: PROXY_DOWNLOAD_URL
                  name: bd-prd-scraper-secret
            - name: QUERY_SIZE
              valueFrom:
                secretKeyRef:
                  key: QUERY_SIZE
                  name: bd-prd-scraper-secret
