apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-scraper
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-scraper
  replicas: 0
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bd-prd-scraper
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: bd-prd-scraper
          image: quay.io/bot_detector/bd-scraper:e73ddab
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 4
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: bd-prd-scraper-secret
            - name: PROXY_DOWNLOAD_URL
              valueFrom:
                secretKeyRef:
                  key: PROXY_DOWNLOAD_URL
                  name: bd-prd-scraper-secret
            - name: PROXY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: PROXY_API_KEY
                  name: bd-prd-scraper-secret
            - name: ENDPOINT
              value: http://bd-dvp-api-service.bd-dvp.svc:5000
            - name: QUERY_SIZE
              value: '10000'
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
            - name: SESSION_TIMEOUT
              value: '60'
