apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-scraper
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: bd-prd-scraper
  replicas: 2
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: bd-prd-scraper
    spec:
      containers:
        - name: bd-prd-scraper
          image: quay.io/bot_detector/bd-scraper:b94d663
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: bd-prd-scraper-secret
            - name: PROXY_DOWNLOAD_URL
              valueFrom:
                secretKeyRef:
                  key: PROXY_DOWNLOAD_URL
                  name: bd-prd-scraper-secret
            - name: ENDPOINT
              value: http://bd-dvp-api-service.bd-dvp.svc:5000
            - name: QUERY_SIZE
              value: '10000'
            - name: KAFKA_HOST
              value: kafka-service.kafka.svc:9092
