apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-prd-kafdrop
  namespace: kafka
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bd-prd-kafdrop
  template:
    metadata:
      labels:
        app: bd-prd-kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          resources:
            requests:
              memory: 600Mi
              cpu: 200m
          env:
            - name: KAFKA_BROKERCONNECT
              value: kafka-service.kafka.svc:9092 # bd-prd-api-service.bd-prd.svc:5000
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
          ports:
            - containerPort: 9000
              name: kafdrop-port
