apiVersion: v1
kind: Service
metadata:
  name: bd-prd-kafdrop-service
  namespace: kafka
spec:
  selector:
    app: bd-prd-kafdrop
  ports:
    - name: kafdrop-port
      port: 9000
      protocol: TCP
      targetPort: kafdrop-port