apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ml
  namespace: bd-prd
spec:
  selector:
    matchLabels:
      app: worker-ml
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: worker-ml
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql
                topologyKey: kubernetes.io/hostname
      containers:
        - name: worker-ml
          image: quay.io/bot_detector/ml-worker:130caa5
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service.kafka.svc:9092
            - name: MAX_MESSAGES
              value: '10000'
            - name: MAX_INTERVAL_MS
              value: '5000'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ml-worker
                  key: DATABASE_URL
            - name: POOL_TIMEOUT
              value: '25'
            - name: POOL_RECYCLE
              value: '25'
            - name: DB_DEBUG
              value: '0'
            - name: BASE_URL
              value: http://ml-api-svc.bd-prd.svc:5000
            - name: MODEL_NAME
              value: multi_model_v1
